/* *** THIS FILE IS GENERATED BY A REALLY SMART ROBOT.      ***
   *** IF YOU EDIT THIS FILE, THE ROBOT WILL EAT YOUR CODE, ***
   *** AND REPLACE YOUR CODE WITH HIS, BECAUSE THAT'S HOW   ***
   *** HE ROLLS. YOU HAVE BEEN WARNED.                      ***

   *** Seriously, if you want to make changes to this file, ***
   *** either run the template that created it again,       ***
   *** or change the template code, at the project path     ***
   *** below.                                               ***

   *** DB.Models/Code Templates/TextTemplate.tt     ***
*/
namespace DB.DAL.CORE
{
    using DB.Models.Core.DB;
    using InteractivePreGeneratedViews;
	using log4net;
	 
	using System.Data.Entity;

	public partial class ContextDb : DbContext
	{
		#region static members

		public static ILog Log { get; set; }

		#endregion

		#region static constructor

		static ContextDb()
		{
			Database.SetInitializer<ContextDb>(null);
			Log = LogManager.GetLogger(typeof(ContextDb));
			using (var ctx = new ContextDb())
			{
				InteractiveViews
					.SetViewCacheFactory(
						ctx,
						new SqlServerViewCacheFactory(ctx.Database.Connection.ConnectionString));
			}
		}

		#endregion

		#region instance properties

		public int MetricId { get; set; }
		public bool SkipLogging { get; set; }

		#endregion

		#region member datasets

		public DbSet<AspNetRoleClaimsModel> AspNetRoleClaimsModel { get; set; }
		public DbSet<AspNetRolesModel> AspNetRolesModel { get; set; }
		public DbSet<AspNetUserClaimsModel> AspNetUserClaimsModel { get; set; }
		public DbSet<AspNetUserLoginsModel> AspNetUserLoginsModel { get; set; }
		public DbSet<AspNetUserRolesModel> AspNetUserRolesModel { get; set; }
		public DbSet<AspNetUsersModel> AspNetUsersModel { get; set; }
		public DbSet<AspNetUserTokensModel> AspNetUserTokensModel { get; set; }
		public DbSet<ConsultantCommentsModel> ConsultantCommentsModel { get; set; }
		public DbSet<ConsultantFollowersModel> ConsultantFollowersModel { get; set; }
		public DbSet<ConsultantLikesModel> ConsultantLikesModel { get; set; }
		public DbSet<ConsultantModel> ConsultantModel { get; set; }
		public DbSet<ConsultantPostMediaModel> ConsultantPostMediaModel { get; set; }
		public DbSet<ConsultantPostModel> ConsultantPostModel { get; set; }
		public DbSet<EventAttendeesModel> EventAttendeesModel { get; set; }
		public DbSet<EventModel> EventModel { get; set; }
		public DbSet<ExpertiseAreaModel> ExpertiseAreaModel { get; set; }
		public DbSet<GroupCategoriesModel> GroupCategoriesModel { get; set; }
		public DbSet<GroupCommentsModel> GroupCommentsModel { get; set; }
		public DbSet<GroupLikesModel> GroupLikesModel { get; set; }
		public DbSet<GroupMembersModel> GroupMembersModel { get; set; }
		public DbSet<GroupModel> GroupModel { get; set; }
		public DbSet<GroupPostMediaModel> GroupPostMediaModel { get; set; }
		public DbSet<GroupPostModel> GroupPostModel { get; set; }
		public DbSet<GroupTypeModel> GroupTypeModel { get; set; }
		public DbSet<TestTblCustomerModel> TestTblCustomerModel { get; set; }
		public DbSet<UserActivityModel> UserActivityModel { get; set; }
		public DbSet<UserCommentsModel> UserCommentsModel { get; set; }
		public DbSet<UserFollowersModel> UserFollowersModel { get; set; }
		public DbSet<UserLikesModel> UserLikesModel { get; set; }
		public DbSet<UserModel> UserModel { get; set; }
		public DbSet<UserPostMediaModel> UserPostMediaModel { get; set; }
		public DbSet<UserPostModel> UserPostModel { get; set; }
		public DbSet<WorkExpModel> WorkExpModel { get; set; }

		#endregion

		#region Entity Framework configuration

		protected override void OnModelCreating(DbModelBuilder modelBuilder)
		{
			base.OnModelCreating(modelBuilder);
		}

		#endregion
	}
}
