/* *** THIS FILE IS GENERATED BY A REALLY SMART ROBOT.      ***
   *** IF YOU EDIT THIS FILE, THE ROBOT WILL EAT YOUR CODE, ***
   *** AND REPLACE YOUR CODE WITH HIS, BECAUSE THAT'S HOW   ***
   *** HE ROLLS. YOU HAVE BEEN WARNED.                      ***

   *** Seriously, if you want to make changes to this file, ***
   *** either run the template that created it again,       ***
   *** or change the template code, at the project path     ***
   *** below.                                               ***

   *** DB.Models/Code Templates/TextTemplate.tt     ***
*/
using DGDean.Models.Base;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB.Models.Core.DB
{
	[Table("AspNetUserTokens", Schema = "dbo")]
	public partial class AspNetUserTokensModel : BaseModel
	{
		#region normal properties

		[Key, Column(Order = 2), Display(Name = "Login Provider"), MaxLength(128), Required(AllowEmptyStrings = true)]
		public string LoginProvider { get; set; }

		[Key, Column(Order = 3), Display(Name = "Name"), MaxLength(128), Required(AllowEmptyStrings = true)]
		public string Name { get; set; }

		[Key, Column(Order = 1), Display(Name = "User Id"), ForeignKey("User"), MaxLength(450), Required(AllowEmptyStrings = true)]
		public string UserId { get; set; }

		[Display(Name = "Value")]
		public string Value { get; set; }

		#endregion

		#region navigation properties

		[ForeignKey("UserId")]
		public virtual AspNetUsersModel User { get; set; }

		#endregion
	}
}
