/* *** THIS FILE IS GENERATED BY A REALLY SMART ROBOT.      ***
   *** IF YOU EDIT THIS FILE, THE ROBOT WILL EAT YOUR CODE, ***
   *** AND REPLACE YOUR CODE WITH HIS, BECAUSE THAT'S HOW   ***
   *** HE ROLLS. YOU HAVE BEEN WARNED.                      ***

   *** Seriously, if you want to make changes to this file, ***
   *** either run the template that created it again,       ***
   *** or change the template code, at the project path     ***
   *** below.                                               ***

   *** DB.Models/Code Templates/TextTemplate.tt     ***
*/
using DGDean.Models.Base;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB.Models.Core.DB
{
	[Table("AspNetRoles", Schema = "dbo")]
	public partial class AspNetRolesModel : BaseModel
	{
		#region normal properties

		[Display(Name = "Concurrency Stamp")]
		public string ConcurrencyStamp { get; set; }

		[Key, Display(Name = "Id"), MaxLength(450), Required(AllowEmptyStrings = true)]
		public string Id { get; set; }

		[Display(Name = "Name"), MaxLength(256)]
		public string Name { get; set; }

		[Display(Name = "Normalized Name"), Index("RoleNameIndex"), MaxLength(256)]
		public string NormalizedName { get; set; }

		#endregion

		#region navigation properties

		[InverseProperty("Role")]
		public virtual ICollection<AspNetRoleClaimsModel> AspNetRoleClaimsModels { get; set; }

		[InverseProperty("Role")]
		public virtual ICollection<AspNetUserRolesModel> AspNetUserRolesModels { get; set; }

		#endregion
	}
}
