/* *** THIS FILE IS GENERATED BY A REALLY SMART ROBOT.      ***
   *** IF YOU EDIT THIS FILE, THE ROBOT WILL EAT YOUR CODE, ***
   *** AND REPLACE YOUR CODE WITH HIS, BECAUSE THAT'S HOW   ***
   *** HE ROLLS. YOU HAVE BEEN WARNED.                      ***

   *** Seriously, if you want to make changes to this file, ***
   *** either run the template that created it again,       ***
   *** or change the template code, at the project path     ***
   *** below.                                               ***

   *** DB.Models/Code Templates/TextTemplate.tt     ***
*/
using DGDean.Models.Attributes;
using DGDean.Models.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB.Models.Core.DB
{
	[Table("Group", Schema = "dbo")]
	public partial class GroupModel : BaseModel
	{
		#region normal properties

		[Display(Name = "Approval Date")]
		public DateTime? ApprovalDate { get; set; }

		[Display(Name = "Consultant Id")]
		public int? ConsultantId { get; set; }

		[Display(Name = "Cover Image"), MaxLength(300)]
		public string CoverImage { get; set; }

		[Display(Name = "Create Date")]
		public DateTime CreateDate { get; set; }

		[Display(Name = "Description")]
		public string Description { get; set; }

		[Display(Name = "Group Category Id")]
		public int? GroupCategoryId { get; set; }

		[Display(Name = "Group Type")]
		public int GroupType { get; set; }

		[Key, DatabaseGenerated(DatabaseGeneratedOption.Identity), Display(Name = "Id")]
		public int Id { get; set; }

		[Display(Name = "Image Name"), MaxLength(300)]
		public string ImageName { get; set; }

		[Active(true), Display(Name = "Is Active")]
		public bool IsActive { get; set; } = true;

		[Display(Name = "Is Approved")]
		public bool IsApproved { get; set; } = false;

		[Display(Name = "Name"), MaxLength(150), Required(AllowEmptyStrings = true)]
		public string Name { get; set; }

		[Display(Name = "Update Date")]
		public DateTime? UpdateDate { get; set; }

		[Display(Name = "User Id")]
		public int? UserId { get; set; }

		[Display(Name = "What Will You Learn")]
		public string WhatWillYouLearn { get; set; }

		#endregion

		#region navigation properties

		[ForeignKey("GroupCategoryId")]
		public virtual GroupCategoriesModel GroupCategory { get; set; }

		[InverseProperty("Group")]
		public virtual ICollection<GroupMembersModel> GroupMembersModels { get; set; }

		[InverseProperty("Group")]
		public virtual ICollection<GroupPostModel> GroupPostModels { get; set; }

		[ForeignKey("GroupType")]
		public virtual GroupTypeModel GroupTypeModel { get; set; }

		#endregion
	}
}
