/* *** THIS FILE IS GENERATED BY A REALLY SMART ROBOT.      ***
   *** IF YOU EDIT THIS FILE, THE ROBOT WILL EAT YOUR CODE, ***
   *** AND REPLACE YOUR CODE WITH HIS, BECAUSE THAT'S HOW   ***
   *** HE ROLLS. YOU HAVE BEEN WARNED.                      ***

   *** Seriously, if you want to make changes to this file, ***
   *** either run the template that created it again,       ***
   *** or change the template code, at the project path     ***
   *** below.                                               ***

   *** DB.Models/Code Templates/TextTemplate.tt     ***
*/
using DGDean.Models.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB.Models.Core.DB
{
	[Table("GroupPost", Schema = "dbo")]
	public partial class GroupPostModel : BaseModel
	{
		#region normal properties

		[Display(Name = "Consultant Id")]
		public int? ConsultantId { get; set; }

		[Display(Name = "Create Date")]
		public DateTime CreateDate { get; set; }

		[Display(Name = "Description")]
		public string Description { get; set; }

		[Display(Name = "Group Id")]
		public int GroupId { get; set; }

		[Key, DatabaseGenerated(DatabaseGeneratedOption.Identity), Display(Name = "Id")]
		public int Id { get; set; }

		[Display(Name = "Update Date")]
		public DateTime? UpdateDate { get; set; }

		[Display(Name = "User Id")]
		public int? UserId { get; set; }

		#endregion

		#region navigation properties

		[ForeignKey("GroupId")]
		public virtual GroupModel Group { get; set; }

		[InverseProperty("GroupPost")]
		public virtual ICollection<GroupPostMediaModel> GroupPostMediaModels { get; set; }

		#endregion
	}
}
