/* *** THIS FILE IS GENERATED BY A REALLY SMART ROBOT.      ***
   *** IF YOU EDIT THIS FILE, THE ROBOT WILL EAT YOUR CODE, ***
   *** AND REPLACE YOUR CODE WITH HIS, BECAUSE THAT'S HOW   ***
   *** HE ROLLS. YOU HAVE BEEN WARNED.                      ***

   *** Seriously, if you want to make changes to this file, ***
   *** either run the template that created it again,       ***
   *** or change the template code, at the project path     ***
   *** below.                                               ***

   *** DB.Models/Code Templates/TextTemplate.tt     ***
*/
using DGDean.Models.Base;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB.Models.Core.DB
{
	[Table("Test_Tbl_Customer", Schema = "samkush3010")]
	public partial class TestTblCustomerModel : BaseModel
	{
		#region normal properties

		[Display(Name = "Customer Name"), MaxLength(50)]
		public string CustomerName { get; set; }

		[Display(Name = "Email Address"), MaxLength(50)]
		public string EmailAddress { get; set; }

		[Key, Column("Test_Tbl_Customer_ID"), DatabaseGenerated(DatabaseGeneratedOption.Identity), Display(Name = "Test_Tbl_Customer_ID")]
		public int TestTblCustomerId { get; set; }

		#endregion
	}
}
