/* *** THIS FILE IS GENERATED BY A REALLY SMART ROBOT.      ***
   *** IF YOU EDIT THIS FILE, THE ROBOT WILL EAT YOUR CODE, ***
   *** AND REPLACE YOUR CODE WITH HIS, BECAUSE THAT'S HOW   ***
   *** HE ROLLS. YOU HAVE BEEN WARNED.                      ***

   *** Seriously, if you want to make changes to this file, ***
   *** either run the template that created it again,       ***
   *** or change the template code, at the project path     ***
   *** below.                                               ***

   *** DB.Models/Code Templates/TextTemplate.tt     ***
*/
using DGDean.Models.Base;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB.Models.Core.DB
{
	[Table("UserActivity", Schema = "dbo")]
	public partial class UserActivityModel : BaseModel
	{
		#region normal properties

		[Display(Name = "Activity Date")]
		public DateTime ActivityDate { get; set; }

		[Display(Name = "Activity Type"), MaxLength(100)]
		public string ActivityType { get; set; }

		[Display(Name = "Consultant Id")]
		public int? ConsultantId { get; set; }

		[Display(Name = "Description"), MaxLength(500), Required(AllowEmptyStrings = true)]
		public string Description { get; set; }

		[Key, DatabaseGenerated(DatabaseGeneratedOption.Identity), Display(Name = "Id")]
		public int Id { get; set; }

		[Display(Name = "Link Url"), MaxLength(500)]
		public string LinkUrl { get; set; }

		[Display(Name = "User Id")]
		public int? UserId { get; set; }

		#endregion
	}
}
