/* *** THIS FILE IS GENERATED BY A REALLY SMART ROBOT.      ***
   *** IF YOU EDIT THIS FILE, THE ROBOT WILL EAT YOUR CODE, ***
   *** AND REPLACE YOUR CODE WITH HIS, BECAUSE THAT'S HOW   ***
   *** HE ROLLS. YOU HAVE BEEN WARNED.                      ***

   *** Seriously, if you want to make changes to this file, ***
   *** either run the template that created it again,       ***
   *** or change the template code, at the project path     ***
   *** below.                                               ***

   *** DB.Models/Code Templates/TextTemplate.tt     ***
*/
using DGDean.Models.Base;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DB.Models.Core.DB
{
	[Table("UserLikes", Schema = "dbo")]
	public partial class UserLikesModel : BaseModel
	{
		#region normal properties

		[Display(Name = "Consultant Id")]
		public int? ConsultantId { get; set; }

		[Key, DatabaseGenerated(DatabaseGeneratedOption.Identity), Display(Name = "Id")]
		public int Id { get; set; }

		[Display(Name = "User Id")]
		public int? UserId { get; set; }

		[Display(Name = "User Post Id")]
		public int UserPostId { get; set; }

		#endregion

		#region navigation properties

		[ForeignKey("ConsultantId")]
		public virtual ConsultantModel Consultant { get; set; }

		[ForeignKey("UserId")]
		public virtual UserModel User { get; set; }

		[ForeignKey("UserPostId")]
		public virtual UserPostModel UserPost { get; set; }

		#endregion
	}
}
